### ISSUE TITLE
插件很好用，但是有几个问题想反馈下

### ISSUE THREAD

**Issue by ryanwlb** [muzuiget/netsub-support#1]
1.我设置双字幕第一字幕中文，第二字幕英文，这时候屏幕会显示三种字幕（neiflix自带的字幕），如果我关闭官方设置字幕会显示插件的两种字幕，但是每次都要设置下，要不然下一集就会没有字幕

**Comment by ryanwlb** [comment]
还有每次关闭网页重新打开都要重新设置下第1  2字幕问题，不能自动保存我的设置

**Comment by muzuiget** [comment]
第一个问题，原生字幕还起作用，这是有意这样做的。两个原因：

1. 避免破坏官方代码，这样兼容性好点，这样可以避免和 netflix-1080p 之类的扩展冲突。
2. 某些字幕，例如日语字幕，原生渲染的是图片型字幕，图片型字幕无法二次处理，也就是无法改变颜色和字体的。甚至自带假名标注，以及竖排。

考虑到有些人可能偏向用原生，再另外加一种语言，所以不接管原生的字幕渲染。

第二个问题，这种功能迟点会加上。
